### ISSUE TITLE
no readme

### ISSUE THREAD

**Issue by KernFerm** [halfuwu/FortnitePortingServerUnreal#11]
no readme ,

**Comment by Tevtongermany** [comment]
why would you need a readme?

**Comment by KernFerm** [comment]
To be able to run and use it lol 

That's what a Readme is for

**Comment by Ka1serM** [comment]
This Plugin works like any other UE Plugin, so there is no need for a readme imo. Also you might want to check out this pr: https://github.com/halfuwu/FortnitePortingServerUnreal/pull/10 if you are on FortnitePorting 2.0

**Comment by KernFerm** [comment]
Dev won't create a Readme,  seen people asking for as not just me
