### ISSUE TITLE
[Major] Fortnite Base Material is incorrect

### ISSUE THREAD

**Issue by AyeTSG** [halfuwu/FortnitePortingServerUnreal#4]
It appears the Fortnite Base Material being used within the plugin is incorrect. Below is an example of importing the `Remus` Pet. The Pet should appear dark grey with light grey underfur, but instead appears mostly white due to the faulty material.

![UnrealEditor_HC9FQfDPT7](https://user-images.githubusercontent.com/49595354/230705813-8e81aae1-ac09-48a2-8cda-0bf24e70a50e.png)

**Comment by h4lfheart** [comment]
this is not a fortnite porting issue, materials will not transfer with any 3d format so you have to - redo the mats yourself

**Comment by AyeTSG** [comment]
I believe it IS a FortnitePorting issue though, as the M_FortnitePorting_Default material is the root cause of this issue. That material is broken is what I'm trying to say

**Comment by halfuwu** [comment]
oh damn I didn't realize this was on the unreal plugin repo that's my bad

i really can't give support on the unreal version because it's heavily in beta but I will figure out why the diffuse texture isn't being added and will fix as soon as I can

**Comment by h4lfheart** [comment]
oop that's my bad!! thought this was the main repo lol

for whatever reason the material changes i made never saved, should be fixed in latest commit

![image](https://user-images.githubusercontent.com/69497698/230726137-b5872b9c-20e0-4a25-a50f-84a376d2acb2.png)

**Comment by AyeTSG** [comment]
Gotcha, i'll test out latest and see how it works!

**Comment by AyeTSG** [comment]
Can confirm that [f016b09](https://github.com/halfuwu/FortnitePortingServerUnreal/commit/f016b094af6de1579d0a16f6447f0e2698a5abd4) fixes this issue.

Safe to close.
