### ISSUE TITLE
[Unreal] Emote importing not working

### ISSUE THREAD

**Issue by AyeTSG** [halfuwu/FortnitePortingServerUnreal#6]
When importing an emote into Unreal Engine, nothing appears to happen. The plugin gives the following output from the engine when importing the Accolades emote:
```
LogFortnitePorting: Received Import for Dance: Accolades
```

Is this currently intended behavior, or is emote importing not yet implemented into the unreal server plugin?

**Comment by h4lfheart** [comment]
maybe check the source first, this plugin is heavily beta and unfinished im not giving any official support on it yet
